# Generated by Django 4.1.13 on 2024-04-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
