# Generated by Django 4.1.13 on 2024-04-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
