# Generated by Django 4.1.13 on 2024-04-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_personaldetails_email_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='grade',
        ),
        migrations.AddField(
            model_name='education',
            name='percent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
